### ISSUE TITLE
Feedback Milestone 2

### ISSUE THREAD

**Issue by pradm007** [data301-2021-summer2/project-group6-project#3]
Hello Group 6, 

My name is Pradeep and I will be giving you some feedback on your project. 

Overall, the project is a fantastic start and there are some suggestions I have that will improve the quality of your project

I have divided up the feedback into several sections so it is easier for you to implement.

## Task 1

- Well done

## Task 2

- Good work on adding brief comments.

## Task 3

- Good work. Please add a description for each plot as to why do you feel they are relevant and how does it help you draw conclusion towards your research question

## Task 4

- Well Done
- Please add a brief summary on which plots/activities that you performed made you reach your conclusion. Also on what more would you have expected for better and easier analysis for your research problem statement.

Overall well done

**Comment by ValWood2021** [comment]
Hi! Thank you for your feedback Pradeep. I will work on it this evening and update my project soon :)

**Comment by ValWood2021** [comment]
Hi Pradeep, I have applied your feedback to Task 4 in my Analysis jupyter notebook. I will work on Task 3 today in my EDA jupyter notebook.

**Comment by ValWood2021** [comment]
Hello again, I also just applied your feedback to Task 3 in my EDA jupyter notebook. Let me know if there's any way I can improve my descriptions. Thank you :)

**Comment by pradm007** [comment]
Very well done. Enjoyed the explainer video. Nice improvement on the EDA.

**Comment by pradm007** [comment]
Closed the issue.
